name: Security audit
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - ".cargo/audit.toml"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
